spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://localhost:3306/peer_vault_db
    username: "{cipher}46a6058b0cd24ecde0da254104b7b93916876e26b6105ec00624b4b168703095"
    password: "{cipher}46a6058b0cd24ecde0da254104b7b93916876e26b6105ec00624b4b168703095"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update




server:
  port: 9095

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
