spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peer_vault_files
    username: root
    password: root64
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update



server:
  port: 9092
  servlet:
    context-path: /file-service

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/service-discovery/eureka/
