spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peer_vault_users
    username: root
    password: root64
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update


server:
  port: 9091
  servlet:
    context-path: /user-service

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/service-discovery/eureka/
